# Generated by Django 5.2.17 on 2026-09-13 00:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('major', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(choices=[('SMA', 'Senior High School'), ('S1', 'Undergraduate Student')], default='S1', max_length=50)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
