# Generated by Django 5.2.17 on 2026-09-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
