# Generated by Django 5.2.17 on 2026-09-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_education_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='ended_at',
        ),
        migrations.RemoveField(
            model_name='education',
            name='started_at',
        ),
    ]
